version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    image: botium/botium-speech-frontend:latest
    restart: always
    environment:
      BOTIUM_API_TOKENS: 
      BOTIUM_SPEECH_PROVIDER_TTS: polly
      BOTIUM_SPEECH_PROVIDER_STT: awstranscribe
      BOTIUM_SPEECH_AWS_REGION:
      BOTIUM_SPEECH_AWS_ACCESS_KEY_ID:
      BOTIUM_SPEECH_AWS_SECRET_ACCESS_KEY:
      BOTIUM_SPEECH_AWS_S3_BUCKET:
    volumes:
      - "./frontend/resources:/app/resources"