FROM botium/kaldi-gstreamer-server:latest

RUN mkdir -p /opt/models && cd /opt/models && \
    wget --no-check-certificate https://goofy.zamia.org/zamia-speech/asr-models/kaldi-generic-de-tdnn_f-r20190328.tar.xz && \
    tar xvJf kaldi-generic-de-tdnn_f-r20190328.tar.xz && \
    sed -i 's:exp/nnet3_chain:/opt/models/kaldi-generic-de-tdnn_f-r20190328:g' /opt/models/kaldi-generic-de-tdnn_f-r20190328/ivectors_test_hires/conf/ivector_extractor.conf

RUN apt-get update && \
    apt-get install -y supervisor && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY models/zamia_20190328_tdnn_f_de.yaml /opt/models/zamia_20190328_tdnn_f_de.yaml
COPY supervisord.kaldi.de.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 80

CMD ["/usr/bin/supervisord"]