FROM openjdk:8-jdk-alpine

RUN apk update && apk upgrade && apk add --no-cache bash git openssh jq

WORKDIR /app
RUN git clone https://github.com/marytts/marytts-installer.git

WORKDIR /app/marytts-installer

RUN cat components.json | jq .[].artifact | xargs ./marytts install

EXPOSE 59125
ENV JAVA_OPTS -Xmx2g
CMD ./marytts
